name: hankshz/python3-test
version: 0.0.1
runtime: py
path: /python3-test
max_concurrency: 1
build:
- docker run --rm -v "$PWD":/worker -w /worker iron/python:3-dev pip install -t packages -r requirements.txt
